delimiter = "|"
eol = "\r\n"

""" Header fields for json string """
field_market_data_request = "ReqMktData"
field_position_data_request = "ReqPositionUpdates"
field_account_data_request = "ReqAccountUpdates"
field_order_data_request = "ReqOrderUpates"
field_send_limit_order = "SendLimitOrder"
field_send_market_order = "SendMarketOrder"
field_contract_id = "ContractId"
field_is_buy = "IsBuy"
field_price = "Price"
field_qty = "Qty"
field_data_command = "DataCommand"  # Returned command field
